services:
  netskyplot-frontend:
    platform: linux/amd64
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "${SSL_CERT_PATH:-/etc/letsencrypt/live/netskyplot.com/fullchain.pem}:/etc/ssl/certs/netskyplot.crt"
      - "${SSL_KEY_PATH:-/etc/letsencrypt/live/netskyplot.com/privkey.pem}:/etc/ssl/private/netskyplot.key"
