name: Auto Deploy to the Server
run-name: ${{ github.actor }} is deploying 🚀

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 167.172.173.179 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -v -i ~/.ssh/id_ed25519 root@167.172.173.179 "echo '✅ SSH Connection successful!'"

      - name: SSH and Deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 root@167.172.173.179 "
            set -e
            cd /netskyplot/frontend &&
            git pull &&
            cd .. &&
            docker compose down &&
            docker compose up -d --build --remove-orphans
          "
